Map
CMPUT301W24T34/SwiftCheckIn pull request #114
Opened 2024-04-01 22:26 UTC by aridge03

Made the map for check in
added a toggle for geolocation permissions 
There was a random error in the file attendee_profile_pic_change.xml ( i did not touch this file but I attempted to fix the error)

2024-04-01 22:47 UTC, aaryansingh-dev requested changes
Please make sure that the DB related methods are in firbase_organizer file. 
Also to avoid getting error due to asynchronous behaviour of the firebase methods, it is best to make callbacks in the firebase class.

2024-04-02 08:19 UTC, aridge03 commented
> Please make sure that the DB related methods are in firbase_organizer file. Also to avoid getting error due to asynchronous behaviour of the firebase methods, it is best to make callbacks in the firebase class.

Changed that and merged with the latest main good catch thank you!

2024-04-02 23:34 UTC, aaryansingh-dev approved these changes

2024-04-02 23:41 UTC, poojabhambri approved these changes

2024-04-02 23:50 UTC, merged