Kunaal
CMPUT301W24T34/SwiftCheckIn pull request #35
Opened 2024-03-02 06:01 UTC by kunaal-gupta

Designed a screen on org side. 
TODO: Add constraints to views

2024-03-02 18:54 UTC, poojabhambri requested changes
Did you put citations for your images/icons?

2024-03-02 18:54 UTC, aridge03 requested changes
I think you need to make citations for your code and images. As well, why are there binary files in your PR? Thank you!

2024-03-02 18:54 UTC, aridge03 commented on app/src/main/res/drawable/notification.png
Are we allowed to use this? With the Canva watermark?

2024-03-02 19:04 UTC, aridge03 requested changes

2024-03-02 19:04 UTC, aridge03 commented on app/src/main/res/layout/event_details.xml
Since it is all text view, we must change this to make it functional and dynamic. For example, the attendee list should be listview, not text view so that we can connect it to firebase.

2024-03-02 19:17 UTC, poojabhambri commented on app/src/main/res/layout/event_details.xml
Could you also fix your textView5 and imageView id's

2024-03-04 01:16 UTC, kunaal-gupta commented on app/src/main/res/drawable/notification.png
These are free images from Canva. I believe Aryan have subscription to use Canava, and if we use that may be we don't need any citation

2024-03-06 16:00 UTC, closed without merging